[tool.poetry]
name = "ciclo"
version = "0.1.4"
description = ""
authors = ["Cristian Garcia <cgarcia.e88@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
jax = ">=0.3.0"
jaxlib = ">=0.3.0"
flax = ">=0.6.0"
tqdm = ">=4.0.0"
pkbar = ">=0.5"
einop = ">=0.0.1"


[tool.poetry.group.dev.dependencies]
black = {version = ">=22.10.0", allow-prereleases = true}
tensorflow-cpu = ">=2.0.0"
tensorflow-datasets = ">=4.0.0"
pytest = "7.1.3"
ipykernel = ">=6.16.1"
mkdocs-material = ">=8.5.10"
mkdocs-jupyter = {version = ">=0.22.0", python = ">=3.7.1,<3.11"}



[tool.poetry.group.all.dependencies]
wandb = "^0.13.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
